### ISSUE TITLE
require? X clustergrammer2/extension

### ISSUE THREAD

**Issue by brobr** [ismms-himc/clustergrammer2#26]
Hi, as the clustergrammer_widget appears very slow with a large dataset, I would like to try the very promising clustergrammer2 but I run into difficulties when trying to get the programme recognised by jupyter. The install was through the normal `python install setup.py` approach.

At the activation stage of the widgets (which depended on the joblib module) this happens:
>bash-5.0# jupyter nbextension enable --py widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
bash-5.0# jupyter nbextension enable --py --sys-prefix clustergrammer2
clustergrammer2 backend version 0.4.0
Enabling notebook extension clustergrammer2/extension...
      - Validating: problems found:
        - require?  X clustergrammer2/extension

What can have gone wrong??

**Comment by cornhundred** [comment]
Hi @brobr, I have not seen that error or tried `python install setup.py` before.

Have you tried to pip install clustergrammer2 (see [link](https://github.com/ismms-himc/clustergrammer2#installation))? 

Also, you can try Clustergrammer2 on Kaggle. See example Kaggle kernel [here](https://www.kaggle.com/cornhundred/heatmap-view-of-modern-era-player-stats) (be sure to set `show_widget` to `True` to show widgets when running the kernel). 

Let us know if any of that works.

**Comment by brobr** [comment]
On Wed, 26 Jun 2019 10:51:42 -0700
Nicolas Fernandez <notifications@github.com> wrote:

> Hi @brobr, I have not seen that error or tried `python install
> setup.py` before.
> 
> Have you tried to pip install clustergrammer2 (see
> [link](https://github.com/ismms-himc/clustergrammer2#installation))? 
> 
> Also, you can try Clustergrammer2 on Kaggle. See example Kaggle
> kernel
> [here](https://www.kaggle.com/cornhundred/heatmap-view-of-modern-era-player-stats)
> (be sure to set `show_widget` to `True` to show widgets when running
> the kernel). 
> 
> Let us know if any of that works.
> 
Hi Nicolas, thanks for the quick response;

Ok, I removed clustergrammer2 that was installed (via a pkg
constructed via 'python3 setup.py install)';  then did a 'pip3 install
clustergrabber2', which used 
"clustergrammer2-0.4.0-py2.py3-none-any.whl ". Now no error when
enabling it as an extension. And now also the example works; but again
running 'net.cluster()' before `net.load_df(df)' threw an error when
'df=pd.read_csv' was used instead of 'net.load_file'.

I had used the clustergrammer2-0.4.0.tar.gz source file which was
compiled before install. What exactly could be the difference for
lacking module needed ? 

And I got the feeling that not all items are
displayed as shown on the Documentation pages (no highlighting of the
'Rearrange' button used; and no way to zoom in... (see attached)

Cheers,

**Comment by cornhundred** [comment]
Hi @brobr, would you be able to share a notebook (e.g. on GitHub) with your issue? You can also try running it on Kaggle (just pip install clustergrammer2 - let me know if you want help with this). 

You should not run `net.cluster()` before loading a DataFrame with `net.load_df(df)`. 

I do need to update the documentation and will be doing this over the upcoming month.

**Comment by brobr** [comment]
Sorry, it's been awhile; needed to get my data first before analyzing them; now I am trying to reorganize them in a proper form and then can try your program again...

Still, also with the updated version I got the same install-error; although a bit of googling gave info how to trace this down:
[https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/37](url)
[https://stackoverflow.com/questions/48655061/error-enabling-python-markdown-extension-for-jupyter-notebooks](url)

Long story short: in my build-script for a clustergrammer2-package (that then can be handled by the slackware pkgtools used to install/remove stuff system-wide) I had to enforce the formation of the folder where the javascript files needed to go and copy these there:
>mkdir -p $PKG/usr/share/jupyter/nbextensions/$PRGNAM
cp $PRGNAM/nbextension/static/*.js $PKG/usr/share/jupyter/nbextensions/$PRGNAM/

then after installation I ran:
>
jupyter nbextension install --py --sys-prefix --symlink clustergrammer2
jupyter nbextension enable --py --sys-prefix clustergrammer2

which no longer gave above error and the clustergrammer-extension seems to be correctly installed:
>bash-5.0$ jupyter nbextension list
Known nbextensions:
  config dir: /usr/etc/jupyter/nbconfig
    notebook section
      plotlywidget/extension  enabled 
      - Validating: OK
      stan_syntax/main  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      clustergrammer2/extension  enabled 
      - Validating: OK

**Comment by brobr** [comment]
PS: Have a look at [https://bqplot.readthedocs.io/en/latest/introduction.html](url)
their install instruction comes with this note:
>jupyter nbextension enable --py --sys-prefix bqplot  # can be skipped for notebook version 5.3 and above

Their setup.py results in the copying of .js files described above as a solution; as seen on the standard.out screen during package building:
>>..
usr/share/
usr/share/jupyter/
usr/share/jupyter/nbextensions/
usr/share/jupyter/nbextensions/bqplot/
usr/share/jupyter/nbextensions/bqplot/extension.js
usr/share/jupyter/nbextensions/bqplot/index.js
usr/share/jupyter/nbextensions/bqplot/index.js.map
..

(I noticed this when creating a package for bqplot  to run your dashboard-experiment)

Just tested whether the clustergrammer2 installation could be done without those nb extension enable commands (being on notebook version 6) and this is the case!
Maybe you could update/simplify your setup.py so that those js files end up directly in the correct place?

BTW, I noticed that clustergrammer does not get/create its own folder in `/usr/etc/jupyter/nbconfig` but a generic `notebook.json` :
>bash-5.0# ls -l /usr/etc/jupyter/nbconfig/notebook.*
-rw-r--r-- 1 root root   68 Mar 27 22:43 /usr/etc/jupyter/nbconfig/notebook.json
>
>/usr/etc/jupyter/nbconfig/notebook.d:
total 16
-rw-r--r-- 1 root root 60 Apr 17  2019 bqplot.json
-rw-r--r-- 1 root root 66 Aug 17  2019 plotlywidget.json
-rw-r--r-- 1 root root 67 Jan  4  2019 stan_syntax.json
-rw-r--r-- 1 root root 72 Jul 29  2019 widgetsnbextension.json

It works, but is this actually wanted? It seems prone to become a bug when another program creates a 'notebook.json' that overwrites the one linking to 'clustergrammer2'?

**Comment by cornhundred** [comment]
Thanks for all the info @brobr we'll let you know if we have any questions trying to implement these suggestions

**Comment by brobr** [comment]
Hi, after getting my data in shape to load in clustergrammer I wonder whether my install is actually correct or maybe incomplete. Comparing the output  in my jupyter notebook to what is in your demos, I get a rather crude control panel (1 in attached image). Also the labels on the left are too big to be readable (2) and there is interaction possible that shows the mouse gene-info (3, which is completely irrelevant in my case).
![controls_label-size_mouse-pop-up_Screenshot_2020-03-29_10-34-26](https://user-images.githubusercontent.com/3693709/77847083-3b3a1100-71b2-11ea-95e9-faa46d6bcb95.png)

Also, I noticed that directly loading of a dataframe seems to bypass the conversion of header-tuples to columns-categories. These are correctly converted when loading the textfile with the data directly. Still the dataframes that are going in appear identical? 

![file-vs-dataframe-load_Screenshot_2020-03-29_10-58-32](https://user-images.githubusercontent.com/3693709/77847876-282a3f80-71b8-11ea-8b62-72aab920d965.png)


[introduction_lab-ipynb.txt](https://github.com/ismms-himc/clustergrammer2/files/4398712/introduction_lab-ipynb.txt)
(you need to convert filename back to ipynb from txt)
[test_to_csv_from_df-ini.txt](https://github.com/ismms-himc/clustergrammer2/files/4398686/test_to_csv_from_df-ini.txt)

**Comment by cornhundred** [comment]
Thanks for all the feedback. I think the following is happening:

1) The control panel might not be rendering correctly because you are not using the Chrome browser (we have to improve our SVG rendering for Mozilla, which is stricter than Chrome). We raised the issue here: https://github.com/ismms-himc/clustergrammer-gl/issues/41

2) The text sizing rules can sometimes result in labels getting cut off, we'll be improving this by improving functionality of Clustergrammer-GL (https://github.com/ismms-himc/clustergrammer-gl/issues/7)

3) We currently always look up gene level information from Harmonizome, but we will allow the option of turning off Harmonizome gene lookup - see issue https://github.com/ismms-himc/clustergrammer-gl/issues/42

4) I think you have to parse the column name strings into tuples see https://stackoverflow.com/questions/9763116/parse-a-tuple-from-a-string/9763133 Clustergrammer2 is treating them as strings and doesn't recognize them as tuples.

**Comment by brobr** [comment]
Hi Nicolas, thanks for the prompt reply! 
(How could you see I ran the notebook on Mozilla/Firefox, was that in the code?)

The tuple advice was spot on: correcting the index results in getting the bar! (The columns-tuple has not been corrected (yet)).

![tuple-issue_spot-on_Screenshot_2020-03-29_18-00-09](https://user-images.githubusercontent.com/3693709/77855570-22991d80-71e9-11ea-95b8-81fd6c2f0a68.png)

And the chosen setting is visible  now. I ran the notebook in Vivaldi, based on chrome. BTW, my platform is Slackware64 linux  (current), python-3.8.

**Comment by cornhundred** [comment]
@brobr, great I'm glad that worked! I've seen the control panel button issue in Firefox so I figured that was the issue. 

I'l go ahead and close the issue since the remaining issues are addressed elsewhere. Feel free to reopen if you would like.

**Comment by brobr** [comment]
Ok. I find that when building the headers with a line like:
>tuplind=[('Experiment: {}'.format(x) , 'Method: {}'.format(y) ) for x,y in zip(index1,index2)]

(index1 and index2 are lists of experiments and associated methods, respectively)

and then set the columns index (can only done after transposing):
>\## because Pandas doesn't allow columns to be created via a new attribute name
\## - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
df2=df_meta0.T
df2.index=tuplind
df_meta02=df2.T

then

>from clustergrammer2 import net, Network
net.load_df(df_meta02)
net.widget()

works

But the tuple info is lost during saving to csv. Thus when reloading a datafile from text to be displayed in clustergrammer, this need to go via:

>net.load_file('exp_29Mar20.txt')
df3 = net.export_df()

and then, as above
>net.load_df(df3)
net.widget()

This distinction can be confusing, especially as multiple-index headers can be easily made in pandas and saved to csv but these are not recognized by clustergrammer as it only detects one line as header and then search for its category lines.

So clustergrammer enforces its own fileformat (based on excell files as source) but maybe -for easy exchange/testing of the same datafiles- it would be good if clustergrammer could directly parse named, multi-indexed headers as well.

Now, for testing the same data, a separate datafile needs to be made for a site as [https://biit.cs.ut.ee/clustvis/](url), which recognizes multi-indexed headers but not the tuple-notation in a file prepared for loading in clustergrammer.

BTW from that site one can export svg, or pdf files for the obtained diagrams. Can this be done with clustergrammer as well (screenshots are not always sufficient)?

**Comment by cornhundred** [comment]
thanks for the feedback @brobr, we'll look into that file format you referenced.
