### ISSUE TITLE
custom matrix tile color scheme

### ISSUE THREAD

**Issue by cornhundred** [ismms-himc/clustergrammer2#39]
**Is your feature request related to a problem? Please describe.**
I want to be able to change the color scheme - currently it is only red/blue for positive/negative values, respectively. 

**Describe the solution you'd like**
I would like to be able to pass in two colors into the `net.widget` method (e.g. named colors or hexcode) and have those override the positive/negative colors.

**Additional context**
This issue depends on this issue in Clustergrammer-GL https://github.com/ismms-himc/clustergrammer-gl/issues/33

**Comment by Fedorov113** [comment]
Any progress on this?

**Comment by cornhundred** [comment]
Not yet, but we'll put it as a high priority

**Comment by llniu** [comment]
Hi, I have a question related to the heat map colour setting as well. Is it possible to set the min. and max. limits of the color bar? Thanks a lot! :)

**Comment by cornhundred** [comment]
Hi @llniu, we currently don't support that (but will add this to the to do list). Currently the way I approach this is to clip the values of the matrix using the 

`net.clip(-5,5)`

method. This is not ideal because you are changing your underlying data before visualizing and we would rather have a method to set the min/max limits of opacity as you suggested.

**Comment by cornhundred** [comment]
Hi @Fedorov113 this can be done as of Clustergrammer2 version 0.8.0

```
net.load_df(df)
net.set_matrix_colors(pos='green', neg='blue')
net.widget()
```

@llniu, we'll be releasing an update soon with a slider that will control the min/max values of the heatmap colors and can be initialized via a method (as well as adjusted on the front-end)

**Comment by cornhundred** [comment]
@llniu version 0.9.0 includes a slider that can be used to scale the opacity. Currently, we're just showing the scaling factor, but plan on also showing the values that are associated with maximum opacity as well as allowing users to set the default opacity from a method on the `net` object.

**Comment by matrs** [comment]
I was trying colors' names from [here](https://www.d3-graph-gallery.com/graph/custom_color.html) and just a few of them worked. What are the valid  color names?  maybe a list of them can be helpful.

**Comment by cornhundred** [comment]
Hi @matrs, our named colors are being defined here (https://github.com/ismms-himc/clustergrammer-gl/blob/8eea42a8a7ac7af9806381468a516ec9935bc37f/src/colors/color_table.js) and we will add this to the documentation. Your safest bet is to use hexcodes for now.

**Comment by matrs** [comment]
Thanks!
