### ISSUE TITLE
Notebook on mybinder does not execute cells automatically

### ISSUE THREAD

**Issue by AviMaayan** [ismms-himc/clustergrammer2#43]
To see the visualization, you need to execute each cell first. This is not convenient.

**Comment by cornhundred** [comment]
Thank you for the feedback. I'm not sure if there's a way to get the notebook to execute automatically on MyBinder (aside from running all cells from the menubar). The static NBViewer option would be better for users who do not want to execute the notebook. 

See examples here: https://github.com/ismms-himc/clustergrammer2-notebooks
