### ISSUE TITLE
Widget not displayed in Jupyter Lab

### ISSUE THREAD

**Issue by MikhaelManurung** [ismms-himc/clustergrammer2#82]
I am trying clustergrammer2 using Jupyter Lab 2.2.8. I can install the package, load my `DataFrame`, but when running `net.widget()`, there was no error message and nothing was displayed. I am using the Chrome browser.

Below is the output of `jupyter labextension list`:

```
JupyterLab v2.2.8
Known labextensions:
   app dir: ___________________________
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        clustergrammer2 v0.17.0  enabled  OK
```

Thanks in advance for your help.

Best regards,

**Comment by slee5777** [comment]
After enabling the extension manager, the widget works perfectly.  

Reference: https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#using-the-extension-manager

![image](https://user-images.githubusercontent.com/28886668/102209101-3f0def00-3f0b-11eb-8c8c-5a2e005a39df.png)
